tdd_app/config/routes.rb
Rails.application.routes.draw do
  get 'customers/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'welcome#index'
  resources :customers
end

tdd_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

tdd_app/app/models/customer.rb
class Customer < ApplicationRecord
    validates :name, presence: true
end

tdd_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

tdd_app/app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]

  def index
    @customers = Customer.all
  end

  def show
  end

  def new
    @customer = Customer.new
  end

  def create 
    @customer = Customer.new(customer_params)
    if @customer.save
      redirect_to customers_path, notice: 'Cliente cadastrado com sucesso!'
    else
      render :new
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: 'Cliente atualizado com sucesso!' }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_path, notice: 'Cliente excluido com sucesso!' }
      format.json { head :no_content }
    end
  end

  private
  def customer_params
    params.require(:customer).permit(:name, :email, :phone, :avatar, :smoker)
  end

  def set_customer
    @customer = Customer.find(params[:id])
  end
end

tdd_app/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

tdd_app/app/helpers/application_helper.rb
module ApplicationHelper
end

tdd_app/app/helpers/customers_helper.rb
module CustomersHelper
end

tdd_app/app/helpers/welcome_helper.rb
module WelcomeHelper
end

tdd_app/app/views/customers/edit.html.erb
<h1>Editar cliente</h1>
<%= render  "customers/shared/form" %>

tdd_app/app/views/customers/index.html.erb
<% if flash[:notice] %>
    <div id='notice'>
        <%= flash[:notice] %>
    </div>
<% end %>

<h1>Listando clientes</h1>

<%= link_to  "Novo cliente", new_customer_path %>

<table>
    <tr>
        <th>Nome</th>
        <th>Email</th>
    </tr>
    <% @customers.each do |customer| %>
        <tr>
            <td> <%= customer.name %> </td>
            <td> <%= customer.email %> </td>
            <td> <%= link_to  "Ver", customer_path(customer) %> </td>
            <td> <%= link_to  "Editar", edit_customer_path(customer) %> </td>
            <td> <%= link_to  "Excluir", customer, method: :delete, data: { confirm: 'Tem certeza?'} %> </td
        </tr>
    <% end %>
</table>

tdd_app/app/views/customers/new.html.erb
<h1>Novo cliente</h1>   

<%= render  "customers/shared/form" %>

tdd_app/app/views/customers/shared/_form.html.erb
<%= form_for(@customer) do |f| %>
    <div>
        <%= f.label :name %>
        <%= f.text_field :name %>
    </div>
    <div>
        <%= f.label :email %>
        <%= f.text_field :email %>
    </div>
    <div>
        <%= f.label :phone %>
        <%= f.text_field :phone %>
    </div>
    <div>
        <%= f.label :avatar %>
        <%= f.file_field :avatar %>
    </div>
    <div>
        <%= f.label :smoker %>
        <% {'S': 'Sim', 'N': 'Não'}.each do |key, value| %>
            <%= f.radio_button :smoker, key %> <%= value %> <br>
        <% end %>
    </div>
    <%= f.submit 'Enviar' %>
<% end %>
<%= link_to  "Voltar", :back %>
<br>
<% if @customer.errors.any? %>
    <ul>
        <% @customer.errors.full_messages.each do |message| %>
            <li><%= message %></li>
        <% end %>
    </ul>
<% end %>

tdd_app/app/views/customers/show.html.erb
<% if flash[:notice] %>
    <div id='notice'>
        <%= flash[:notice] %>
    </div>
<% end %>

<h3>Cliente</h3>
<hr>
<p>
    <strong>Nome:</strong> 
    <%= @customer.name %>
</p>
<p>
    <strong>Email:</strong> 
    <%= @customer.email %>
</p>
<p>
    <strong>Telefone:</strong> 
    <%= @customer.phone %>
</p>
<%= link_to  "Editar", edit_customer_path(@customer) %>
<%= link_to  "Voltar", customers_path %>

tdd_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TddApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

tdd_app/app/views/welcome/index.html.erb
<h1>Bem-vindo!</h1>
<ul>
    <li><%= link_to "Cadastro de Clientes", customers_path %></li>
</ul>